import type { Credit } from "@/lib/db/schema";

// CSR 2026 credits — verify against live Chase cardmember agreement before launch
export const csrCredits: Omit<Credit, "id">[] = [
  {
    cardId: "csr",
    name: "StubHub / viagogo credit (H1)",
    amountCents: 15000,
    description: "$150 StubHub/viagogo credit expires Jun 30. Activation required.",
    activationUrl: "https://www.chase.com/mybonus",
    deadlineType: "calendar",
    deadlineMonth: 6,
    deadlineDay: 30,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "csr",
    name: "StubHub / viagogo credit (H2)",
    amountCents: 15000,
    description: "$150 StubHub/viagogo credit expires Dec 31. Resets Jul 1.",
    activationUrl: "https://www.chase.com/mybonus",
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "csr",
    name: "Exclusive Tables dining (H1)",
    amountCents: 15000,
    description: "$150 Exclusive Tables dining credit expires Jun 30. OpenTable curated list.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 6,
    deadlineDay: 30,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "csr",
    name: "Exclusive Tables dining (H2)",
    amountCents: 15000,
    description: "$150 Exclusive Tables dining credit expires Dec 31.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "csr",
    name: "The Edit hotel credit",
    amountCents: 50000,
    description: "$500 The Edit hotel credit expires Dec 31. Prepaid 2+ night via Chase Travel.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "csr",
    name: "Select Hotels credit",
    amountCents: 25000,
    description: "$250 Select Hotels credit (2026 only). IHG/Montage/Pendry/Omni/Virgin. Expires Dec 31.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "one_time",
    expiresAfterYear: 2026,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "csr",
    name: "Travel credit",
    amountCents: 30000,
    description: "$300 annual travel credit resets on your card anniversary.",
    activationUrl: null,
    deadlineType: "anniversary",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "csr",
    name: "DoorDash restaurant promo",
    amountCents: 500,
    description: "$5 DoorDash restaurant credit expires end of month.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: true,
  },
  {
    cardId: "csr",
    name: "DoorDash non-restaurant promo #1",
    amountCents: 1000,
    description: "$10 DoorDash non-restaurant credit expires end of month.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: true,
  },
  {
    cardId: "csr",
    name: "DoorDash non-restaurant promo #2",
    amountCents: 1000,
    description: "$10 DoorDash non-restaurant credit expires end of month.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: true,
  },
  {
    cardId: "csr",
    name: "Lyft credit",
    amountCents: 1000,
    description: "$10 Lyft credit expires end of month.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: true,
  },
  {
    cardId: "csr",
    name: "Peloton credit",
    amountCents: 1000,
    description: "$10 Peloton credit expires end of month. Activation required.",
    activationUrl: "https://www.chase.com/mybonus",
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: true,
  },
];
