import type { Credit } from "@/lib/db/schema";

export const hiltonAspireCredits: Omit<Credit, "id">[] = [
  {
    cardId: "hilton_aspire",
    name: "Resort credit (H1)",
    amountCents: 20000,
    description: "$200 Hilton resort credit expires Jun 30. Must be at participating resorts.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 6,
    deadlineDay: 30,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "hilton_aspire",
    name: "Resort credit (H2)",
    amountCents: 20000,
    description: "$200 Hilton resort credit expires Dec 31. Must be at participating resorts.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "hilton_aspire",
    name: "Airline/flight credit (Q1)",
    amountCents: 5000,
    description: "$50 airline credit expires Mar 31.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 3,
    deadlineDay: 31,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "hilton_aspire",
    name: "Airline/flight credit (Q2)",
    amountCents: 5000,
    description: "$50 airline credit expires Jun 30.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 6,
    deadlineDay: 30,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "hilton_aspire",
    name: "Airline/flight credit (Q3)",
    amountCents: 5000,
    description: "$50 airline credit expires Sep 30.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 9,
    deadlineDay: 30,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "hilton_aspire",
    name: "Airline/flight credit (Q4)",
    amountCents: 5000,
    description: "$50 airline credit expires Dec 31.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "hilton_aspire",
    name: "CLEAR+ membership credit",
    amountCents: 20900,
    description: "$209 CLEAR+ membership credit expires Dec 31.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
];
