import type { Credit } from "@/lib/db/schema";

export const amexGoldCredits: Omit<Credit, "id">[] = [
  {
    cardId: "amex_gold",
    name: "Uber Cash",
    amountCents: 1000,
    description: "$10/mo Uber Cash. Does not roll over.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: true,
  },
  {
    cardId: "amex_gold",
    name: "Dining credit",
    amountCents: 1000,
    description: "$10/mo dining credit (Grubhub, Cheesecake Factory, Five Guys, etc). Enrollment required.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: true,
  },
  {
    cardId: "amex_gold",
    name: "Dunkin' credit",
    amountCents: 700,
    description: "$7/mo Dunkin' credit. Enrollment required.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: true,
  },
  {
    cardId: "amex_gold",
    name: "Resy restaurant credit (H1)",
    amountCents: 5000,
    description: "$50 Resy dining credit expires Jun 30. Enrollment required.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 6,
    deadlineDay: 30,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_gold",
    name: "Resy restaurant credit (H2)",
    amountCents: 5000,
    description: "$50 Resy dining credit expires Dec 31. Enrollment required.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
];
