import type { Credit } from "@/lib/db/schema";

export const marriottBrilliantCredits: Omit<Credit, "id">[] = [
  {
    cardId: "marriott_brilliant",
    name: "Dining credit",
    amountCents: 2500,
    description: "$25/mo dining credit at any restaurant worldwide. Does not roll over.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "marriott_brilliant",
    name: "Ritz-Carlton / St. Regis property credit (H1)",
    amountCents: 10000,
    description: "$100 Ritz/St. Regis property credit expires Jun 30. 2-night min stay.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 6,
    deadlineDay: 30,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "marriott_brilliant",
    name: "Ritz-Carlton / St. Regis property credit (H2)",
    amountCents: 10000,
    description: "$100 Ritz/St. Regis property credit expires Dec 31. 2-night min stay.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
];
