import type { Credit } from "@/lib/db/schema";

export const amexPlatinumCredits: Omit<Credit, "id">[] = [
  {
    cardId: "amex_platinum",
    name: "Uber Cash",
    amountCents: 1500,
    description: "$15/mo Uber Cash ($20 in Dec). Does not roll over.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: true,
  },
  {
    cardId: "amex_platinum",
    name: "Streaming/Digital Entertainment credit",
    amountCents: 2500,
    description: "$25/mo streaming credit (Disney+, Hulu, ESPN+, Peacock, NYT, WSJ). Enrollment required.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: true,
  },
  {
    cardId: "amex_platinum",
    name: "Resy restaurant credit (Q1)",
    amountCents: 10000,
    description: "$100 Resy dining credit expires Mar 31. Enrollment required.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 3,
    deadlineDay: 31,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "Resy restaurant credit (Q2)",
    amountCents: 10000,
    description: "$100 Resy dining credit expires Jun 30. Enrollment required.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 6,
    deadlineDay: 30,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "Resy restaurant credit (Q3)",
    amountCents: 10000,
    description: "$100 Resy dining credit expires Sep 30. Enrollment required.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 9,
    deadlineDay: 30,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "Resy restaurant credit (Q4)",
    amountCents: 10000,
    description: "$100 Resy dining credit expires Dec 31. Enrollment required.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "Lululemon credit (Q1)",
    amountCents: 7500,
    description: "$75 Lululemon credit expires Mar 31.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 3,
    deadlineDay: 31,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "Lululemon credit (Q2)",
    amountCents: 7500,
    description: "$75 Lululemon credit expires Jun 30.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 6,
    deadlineDay: 30,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "Lululemon credit (Q3)",
    amountCents: 7500,
    description: "$75 Lululemon credit expires Sep 30.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 9,
    deadlineDay: 30,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "Lululemon credit (Q4)",
    amountCents: 7500,
    description: "$75 Lululemon credit expires Dec 31.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "FHR / Hotel Collection credit (H1)",
    amountCents: 30000,
    description: "$300 Fine Hotels + Resorts / Hotel Collection credit expires Jun 30.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 6,
    deadlineDay: 30,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "FHR / Hotel Collection credit (H2)",
    amountCents: 30000,
    description: "$300 Fine Hotels + Resorts / Hotel Collection credit expires Dec 31.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "Airline incidental fee credit",
    amountCents: 20000,
    description: "$200 airline incidental credit expires Dec 31. Must select airline.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "Saks Fifth Avenue credit (H1)",
    amountCents: 5000,
    description: "$50 Saks credit expires Jun 30. Ending July 1, 2026.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 6,
    deadlineDay: 30,
    frequency: "biannual_h1",
    expiresAfterYear: 2026,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "Equinox credit",
    amountCents: 30000,
    description: "$300 Equinox membership credit expires Dec 31. Enrollment required.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "CLEAR+ membership credit",
    amountCents: 20900,
    description: "$209 CLEAR+ membership credit expires Dec 31.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "amex_platinum",
    name: "Global Entry / TSA PreCheck credit",
    amountCents: 12000,
    description: "$120 Global Entry/TSA PreCheck credit. Resets every 4 years.",
    activationUrl: null,
    deadlineType: "anniversary",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
];
