import type { Credit } from "@/lib/db/schema";

// Bank of America Premium Rewards Elite
export const bofaPremiumEliteCredits: Omit<Credit, "id">[] = [
  {
    cardId: "bofa_premium_elite",
    name: "Airline incidental credit",
    amountCents: 30000,
    description: "$300 airline incidental credit (bags, upgrades, in-flight). Expires Dec 31.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "bofa_premium_elite",
    name: "Lifestyle credit",
    amountCents: 15000,
    description: "$150 lifestyle credit (rideshare, food delivery, streaming, fitness). Expires Dec 31.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "bofa_premium_elite",
    name: "Global Entry / TSA PreCheck credit",
    amountCents: 12000,
    description: "$120 Global Entry/TSA PreCheck credit. Resets every 4 years.",
    activationUrl: null,
    deadlineType: "anniversary",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
];

// U.S. Bank Altitude Reserve
export const altitudeReserveCredits: Omit<Credit, "id">[] = [
  {
    cardId: "altitude_reserve",
    name: "Travel credit",
    amountCents: 32500,
    description: "$325 travel credit resets on anniversary. Must book through U.S. Bank Travel Center.",
    activationUrl: null,
    deadlineType: "anniversary",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "altitude_reserve",
    name: "Global Entry / TSA PreCheck credit",
    amountCents: 10000,
    description: "$100 Global Entry/TSA PreCheck credit. Resets every 4 years.",
    activationUrl: null,
    deadlineType: "anniversary",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
];

// World of Hyatt (Chase)
export const worldOfHyattCredits: Omit<Credit, "id">[] = [
  {
    cardId: "world_of_hyatt",
    name: "Anniversary free night certificate",
    amountCents: 25000,
    description: "Free night cert (Cat 1-4, ~$150-400 value). Expires 12 months from issuance.",
    activationUrl: null,
    deadlineType: "anniversary",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
];

// IHG One Rewards Premier (Chase)
export const ihgPremierCredits: Omit<Credit, "id">[] = [
  {
    cardId: "ihg_premier",
    name: "Anniversary free night award",
    amountCents: 20000,
    description: "Free night award (up to 40K pts, ~$150-250 value). Expires 12 months from issuance.",
    activationUrl: null,
    deadlineType: "anniversary",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "ihg_premier",
    name: "United TravelBank Cash (H1)",
    amountCents: 2500,
    description: "$25 United TravelBank deposited ~Jan 5. EXPIRES Jul 15! Must register at ihg.com/united.",
    activationUrl: "https://www.ihg.com/united",
    deadlineType: "calendar",
    deadlineMonth: 7,
    deadlineDay: 15,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "ihg_premier",
    name: "United TravelBank Cash (H2)",
    amountCents: 2500,
    description: "$25 United TravelBank deposited ~Jul 5. EXPIRES Jan 15! Must register at ihg.com/united.",
    activationUrl: "https://www.ihg.com/united",
    deadlineType: "calendar",
    deadlineMonth: 1,
    deadlineDay: 15,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "ihg_premier",
    name: "Global Entry / TSA PreCheck credit",
    amountCents: 12000,
    description: "$120 Global Entry/TSA PreCheck credit. Resets every 4 years.",
    activationUrl: null,
    deadlineType: "anniversary",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
];

// Bilt Palladium
export const biltPalladiumCredits: Omit<Credit, "id">[] = [
  {
    cardId: "bilt_palladium",
    name: "Hotel credit (H1)",
    amountCents: 20000,
    description: "$200 Bilt Travel hotel credit expires Jun 30. Book via Bilt Travel Portal.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 6,
    deadlineDay: 30,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "bilt_palladium",
    name: "Hotel credit (H2)",
    amountCents: 20000,
    description: "$200 Bilt Travel hotel credit expires Dec 31. Book via Bilt Travel Portal.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "bilt_palladium",
    name: "Bilt Cash",
    amountCents: 20000,
    description: "$200 Bilt Cash credited Jan 1. Does not roll over to next year.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "bilt_palladium",
    name: "Grubhub delivery credit",
    amountCents: 1000,
    description: "$10/mo Grubhub credit. Does not roll over.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: true,
  },
  {
    cardId: "bilt_palladium",
    name: "Gopuff credit",
    amountCents: 500,
    description: "$5/mo Gopuff credit. Does not roll over.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: true,
  },
];
