import type { Credit } from "@/lib/db/schema";

export const citiStrataPremierCredits: Omit<Credit, "id">[] = [
  {
    cardId: "citi_strata_premier",
    name: "Hotel credit",
    amountCents: 10000,
    description: "$100 hotel credit (stays $500+). Must book via Citi Travel. Expires Dec 31.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
];

export const citiStrataEliteCredits: Omit<Credit, "id">[] = [
  {
    cardId: "citi_strata_elite",
    name: "Hotel credit",
    amountCents: 30000,
    description: "$300 hotel credit expires Dec 31. Must book 2+ night stay via cititravel.com.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "citi_strata_elite",
    name: "Splurge credit",
    amountCents: 20000,
    description: "$200 Splurge credit expires Dec 31. Must activate merchant selections at citi.com.",
    activationUrl: "https://www.citi.com/splurgecredit",
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "citi_strata_elite",
    name: "Blacklane chauffeur credit (H1)",
    amountCents: 10000,
    description: "$100 Blacklane credit expires Jun 30.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 6,
    deadlineDay: 30,
    frequency: "biannual_h1",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "citi_strata_elite",
    name: "Blacklane chauffeur credit (H2)",
    amountCents: 10000,
    description: "$100 Blacklane credit expires Dec 31.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "biannual_h2",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "citi_strata_elite",
    name: "Global Entry / TSA PreCheck credit",
    amountCents: 12000,
    description: "$120 Global Entry/TSA PreCheck credit. Resets every 4 years.",
    activationUrl: null,
    deadlineType: "anniversary",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
];
