import type { Credit } from "@/lib/db/schema";

export const deltaReserveCredits: Omit<Credit, "id">[] = [
  {
    cardId: "delta_reserve",
    name: "Resy restaurant credit",
    amountCents: 2000,
    description: "$20/mo Resy dining credit. Does not roll over.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "delta_reserve",
    name: "Ride-hailing credit",
    amountCents: 1000,
    description: "$10/mo ride credit (Lyft, Uber, Alto, Curb). Does not roll over.",
    activationUrl: null,
    deadlineType: "rolling_monthly",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "monthly",
    expiresAfterYear: null,
    active: true,
    lowPriority: true,
  },
  {
    cardId: "delta_reserve",
    name: "Delta Stays hotel credit",
    amountCents: 20000,
    description: "$200 Delta Stays hotel credit expires Dec 31. Book via delta.com/stays.",
    activationUrl: null,
    deadlineType: "calendar",
    deadlineMonth: 12,
    deadlineDay: 31,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "delta_reserve",
    name: "Companion certificate",
    amountCents: 0,
    description: "Companion cert for domestic/Caribbean round-trip. Expires ~12 months from issuance.",
    activationUrl: null,
    deadlineType: "anniversary",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
  {
    cardId: "delta_reserve",
    name: "Global Entry / TSA PreCheck credit",
    amountCents: 12000,
    description: "$120 Global Entry/TSA PreCheck credit. Resets every 4 years.",
    activationUrl: null,
    deadlineType: "anniversary",
    deadlineMonth: null,
    deadlineDay: null,
    frequency: "annual",
    expiresAfterYear: null,
    active: true,
    lowPriority: false,
  },
];
